services:
  - type: web
    name: trello-proxy
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: TRELLO_KEY
        sync: false
      - key: TRELLO_TOKEN
        sync: false